---
# Configuración Maestra de Calamares para Elyra Linux
modules-search: [ local, /usr/lib/x86_64-linux-gnu/calamares/modules ]

instances:
- id:       elyra
  module:   branding
  config:   /opt/elyra_dev/calamares/branding.desc

sequence:
- show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
- exec:
    - partition
    - mount
    - unpackfs
    - sources-y-ia      # Aquí es donde vinculamos tus scripts
    - machineid
    - fstab
    - bootloader
    - umount
- show:
    - finished

branding: elyra
prompt-install: true
dont-chroot: false
