defaultGroups:
    - lp
    - video
    - audio
    - cdrom
    - sudo
    - dip
    - plugdev
    - netdev
    - lpadmin
    - scanner
    - bluetooth

userGroup:       users
autologinGroup:  autologin
sudoersGroup:    sudo
setRootPassword: true

passwordRequirements:
    nonempty: true
    minLength: 4      # Un mínimo de 4 para que no sea demasiado inseguro
    maxLength: -1     # Sin límite máximo
    libpwquality:
        - minlen=1    # Permite contraseñas simples si el usuario lo desea
        - minclass=0
